/*
 * Retromod - Backwards Compatibility Layer for Minecraft Mods
 * Copyright (c) 2026 Bownlux. MIT License.
 */
package com.retromod.core;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/**
 * Converts a Fabric access widener into a Forge access transformer.
 *
 * <p>The formats express similar access changes, but use different names and
 * syntax. This converter reshapes the file without remapping symbols. An
 * intermediary widener is therefore rejected until its names can be remapped.
 *
 * <p>The modifier mapping is adapted from Sinytra Connector:
 * <ul>
 *   <li>Class: {@code accessible} to {@code public}, {@code extendable} to {@code public-f}</li>
 *   <li>Method: {@code accessible} to {@code public}, {@code extendable} to {@code protected-f}</li>
 *   <li>Field: {@code accessible} to {@code public}, {@code mutable} to {@code public-f}</li>
 * </ul>
 */
final class AccessWidenerToAtConverter {

    private AccessWidenerToAtConverter() {
    }

    /**
     * Translate AccessWidener text into AccessTransformer text.
     *
     * @return the {@code accesstransformer.cfg} body, or an empty string if the
     *         input yielded no translatable directives
     */
    static String convert(String accessWidenerText) {
        if (accessWidenerText == null || accessWidenerText.isBlank()) {
            return "";
        }

        // Forge cannot resolve intermediary names in an access transformer.
        if (isIntermediaryNamespace(accessWidenerText)) {
            return "";
        }

        List<String> out = new ArrayList<>();
        out.add("# Generated by Retromod from a Fabric access widener.");
        out.add("# Modifier rules adapted from Sinytra Connector (MIT).");

        Set<String> explicitClassOwners = new LinkedHashSet<>();
        Set<String> implicitClassOwners = new LinkedHashSet<>();

        String[] lines = accessWidenerText.split("\n");
        int emitted = 0;

        for (String raw : lines) {
            // Access wideners allow trailing comments.
            int hash = raw.indexOf('#');
            String line = (hash >= 0 ? raw.substring(0, hash) : raw).trim();

            if (line.isEmpty()) {
                continue;
            }

            if (line.toLowerCase(Locale.ROOT).startsWith("accesswidener")) {
                continue;
            }

            String at = convertDirective(line);
            if (at != null) {
                out.add(at);
                emitted++;

                String owner = directiveOwner(line);
                if (isClassDirective(line)) {
                    if (owner != null) explicitClassOwners.add(owner);
                } else if (owner != null) {
                    implicitClassOwners.add(owner);
                }
            }
        }

        if (emitted == 0) {
            return "";
        }

        // A widened member is still unusable when its package-private owner stays closed.
        for (String owner : implicitClassOwners) {
            if (!explicitClassOwners.contains(owner)) {
                out.add("public " + owner + " # implicit owner-widening (AW semantics)");
            }
        }

        return String.join("\n", out) + "\n";
    }

    /** True when the (comment-stripped) directive line is a {@code class} directive. */
    private static boolean isClassDirective(String line) {
        String[] parts = line.split("\\s+");
        return parts.length >= 2 && "class".equalsIgnoreCase(parts[1]);
    }

    /**
     * The dotted owner class of a directive, or null if it isn't a well-formed directive.
     * Mirrors the parsing in {@link #convertDirective} without recomputing the modifier.
     */
    private static String directiveOwner(String line) {
        String[] parts = line.split("\\s+");
        return parts.length >= 3 ? dotted(parts[2]) : null;
    }

    /**
     * Convert a single AW directive line into an AT line, or return null when
     * the directive is not translatable (unknown access verb / target type).
     *
     * <p>AW directives are: {@code <access> <type> <owner> [member] [desc]},
     * where {@code <access>} is accessible/extendable/mutable and {@code <type>}
     * is class/method/field. A {@code transitive-} prefix on the access verb is
     * a Fabric-only build-time hint; strip it.
     */
    private static String convertDirective(String line) {
        String[] parts = line.split("\\s+");
        if (parts.length < 3) {
            return null;
        }

        String access = parts[0].toLowerCase(Locale.ROOT);
        if (access.startsWith("transitive-")) {
            access = access.substring("transitive-".length());
        }
        String type = parts[1].toLowerCase(Locale.ROOT);
        String owner = dotted(parts[2]);

        switch (type) {
            case "class": {
                if (parts.length != 3) {
                    return null;
                }
                String modifier = switch (access) {
                    case "accessible" -> "public";
                    case "extendable" -> "public-f"; // stay subclassable, drop final
                    default -> null;
                };
                return modifier == null ? null : modifier + " " + owner;
            }
            case "method": {
                // <access> method <owner> <name> <descriptor>
                if (parts.length != 5) {
                    return null;
                }
                String modifier = switch (access) {
                    case "accessible" -> "public";
                    case "extendable" -> "protected-f"; // stay overridable, drop final
                    default -> null;
                };
                if (modifier == null) {
                    return null;
                }
                String name = parts[3];
                String desc = parts[4];
                return modifier + " " + owner + " " + name + desc;
            }
            case "field": {
                // <access> field <owner> <name> <descriptor>
                if (parts.length != 5) {
                    return null;
                }
                String modifier = switch (access) {
                    case "accessible" -> "public";
                    case "mutable" -> "public-f"; // drop final so the field is writable
                    default -> null;
                };
                if (modifier == null) {
                    return null;
                }
                String name = parts[3];
                return modifier + " " + owner + " " + name;
            }
            default:
                return null;
        }
    }

    /**
     * True when the AW header declares the {@code intermediary} namespace. The header is the
     * first non-blank, non-comment line: {@code accessWidener v2 <namespace>}. A missing or
     * {@code named}/{@code official} namespace is treated as safe to convert.
     */
    private static boolean isIntermediaryNamespace(String accessWidenerText) {
        for (String raw : accessWidenerText.split("\n")) {
            int hash = raw.indexOf('#');
            String line = (hash >= 0 ? raw.substring(0, hash) : raw).trim();
            if (line.isEmpty()) {
                continue;
            }
            if (!line.toLowerCase(Locale.ROOT).startsWith("accesswidener")) {
                return false; // no header (or first content line isn't one): assume named
            }
            String[] parts = line.split("\\s+");
            // accessWidener <version> <namespace>
            return parts.length >= 3 && "intermediary".equalsIgnoreCase(parts[2]);
        }
        return false;
    }

    /** Convert an internal class name (net/minecraft/Foo) to dotted (net.minecraft.Foo). */
    private static String dotted(String internalName) {
        return internalName.replace('/', '.');
    }
}
