/*
 * Retromod - Backwards Compatibility Layer for Minecraft Mods
 * Copyright (c) 2026 Bownlux. Licensed under MIT License.
 */
package com.retromod.shim.forge.embedded;

import java.util.ArrayList;
import java.util.List;

/**
 * Stand-in for the 1.12.2 {@code ModMetadata} that mods without {@code mcmod.info} filled in from
 * pre-init. The host builds its mod list from the generated toml before any mod code runs, so
 * what the mod writes here is kept but never shown. Fields that held 1.12 loader types
 * ({@code parentMod}, {@code childMods}, the dependency sets) are not provided.
 */
public final class LegacyModMetadata {

    public String modId;
    public String name;
    public String description = "";
    public String url = "";
    public String updateUrl = "";
    public String updateJSON = "";
    public String logoFile = "";
    public String version = "";
    public List<String> authorList = new ArrayList<>(1);
    public String credits = "";
    public String parent = "";
    public String[] screenshots;
    public boolean useDependencyInformation;
    public boolean autogenerated = true;

    public LegacyModMetadata(String modId) {
        this.modId = modId;
        this.name = modId;
    }

    public String getChildModCountString() {
        return "";
    }

    public String getAuthorList() {
        return String.join(", ", authorList);
    }

    public String getChildModList() {
        return "";
    }

    public String printableSortingRules() {
        return "";
    }
}
