#!/usr/bin/env python3
"""Record SRG ids whose Mojang name changed across Forge's SRG era.

Forge kept some SRG ids while the member behind them changed. m_7366_ was
ArmorMaterial.getDurabilityForSlot in 1.19.2 and is getDefenseForType from 1.19.4.
srg-to-mojang.tsv holds one name per id (the 1.20.1 one), so a mod built for the
other side of such a change was renamed to the wrong member.

For every id with more than one Mojang name across the harvested versions, this
writes the version range each name covers, using the same per-version join as
harvest-srg-union.py. Retromod picks the range that contains the mod's own
Minecraft version and falls back to srg-to-mojang.tsv everywhere else.

Usage:  python3 scripts/harvest-srg-drift.py
Output: src/main/resources/retromod/srg-version-drift.tsv
"""
import importlib.util
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
OUT = os.path.join(REPO, "src", "main", "resources", "retromod", "srg-version-drift.tsv")

spec = importlib.util.spec_from_file_location("union", os.path.join(HERE, "harvest-srg-union.py"))
union = importlib.util.module_from_spec(spec)
spec.loader.exec_module(union)


def main():
    per_version = {}
    for version in union.VERSIONS:
        print(f"[{version}] joining...", flush=True)
        per_version[version] = union.join_version(version)

    names = {}
    for version in union.VERSIONS:
        for key, mojang in per_version[version].items():
            names.setdefault(key, []).append((version, mojang))

    rows = []
    for (kind, srg), history in sorted(names.items()):
        if len({mojang for _, mojang in history}) < 2:
            continue
        # Contiguous runs of the same name become one range.
        start, current, last = history[0][0], history[0][1], history[0][0]
        for version, mojang in history[1:]:
            if mojang != current:
                rows.append((kind, srg, start, last, current))
                start, current = version, mojang
            last = version
        rows.append((kind, srg, start, last, current))

    with open(OUT, "w") as out:
        out.write("# SRG ids whose Mojang name changed across Forge's SRG era.\n")
        out.write("# Generated by scripts/harvest-srg-drift.py from MCPConfig and Mojang mappings.\n")
        out.write("# KIND<TAB>SRG<TAB>FIRST_VERSION<TAB>LAST_VERSION<TAB>MOJANG_NAME\n")
        out.write("# A mod built for a version in [FIRST, LAST] means MOJANG_NAME by this id.\n")
        for row in rows:
            out.write("\t".join(row) + "\n")
    drifted = len({(kind, srg) for kind, srg, *_ in rows})
    print(f"{drifted} drifted ids, {len(rows)} ranges -> {OUT}")


if __name__ == "__main__":
    main()
