/*
 * Retromod - Backwards Compatibility Layer for Minecraft Mods
 * Copyright (c) 2026 Bownlux. Licensed under MIT License.
 */
package com.retromod.shim.common;

import com.retromod.core.RetromodTransformer;

/**
 * 26.2 to 26.3 core class moves, shared by the Fabric, NeoForge, and Forge shims. Both versions use
 * Mojang names on every loader, so the table is loader independent, and each loader wraps it in its
 * own shim because the shim registry runs its search per loader.
 *
 * <p>Generated from the 26.2 and 26.3-snapshot-10 client jars. Every entry is checked against both:
 * the old name is present in 26.2 and absent in 26.3, the new name is present in 26.3 and absent in
 * 26.2, and the pairing itself is proven by an identical simple name, a unique structural match, or
 * overlapping members. Nothing inferred from name similarity alone is included.
 *
 * <p>The bulk of the jump is one library repackage: {@code com/mojang/blaze3d} became
 * {@code com/mojang/renderpearl}, with its subpackages reorganized rather than moved wholesale, so
 * each class is listed rather than a prefix rewritten. The repackage is partial: {@code PoseStack},
 * {@code VertexConsumer}, {@code BufferBuilder}, and {@code ByteBufferBuilder} stayed where they
 * were. The rest are vanilla moves, several of which only correct capitalization
 * ({@code EnderMan} to {@code Enderman}, {@code RedStoneWireBlock} to {@code RedstoneWireBlock}).
 *
 * <p>A class move restores linkage, not behavior. A renamed class whose members also changed still
 * needs a member redirect or a bridge, and the rendering repackage in particular carries API drift
 * that a class name alone does not describe.
 *
 * <p>26.3 also deletes much of the worldgen configuration system outright, including
 * {@code FeatureConfiguration} and its subclasses, {@code ConfiguredFeature},
 * {@code SurfaceRules}, {@code BlockStateProviderType}, and {@code PlacementModifierType}, and
 * finishes the data-driven item migration by removing {@code AxeItem}, {@code HoeItem},
 * {@code ShovelItem}, {@code BedItem}, and {@code SignItem}. Those have no successor to point
 * at, so they are absent here and need a real port.
 */
public final class Mc26_2To26_3CoreMoves {

    private Mc26_2To26_3CoreMoves() {}

    public static void register(RetromodTransformer t) {
        registerRenderLibraryRepackage(t);
        registerVanillaMoves(t);
    }

    /** {@code com/mojang/blaze3d} became {@code com/mojang/renderpearl} (182 classes). */
    private static void registerRenderLibraryRepackage(RetromodTransformer t) {
        t.registerClassRedirect("com/mojang/blaze3d/GpuDeviceLossException",
                "com/mojang/renderpearl/api/device/GpuDeviceLossException");
        t.registerClassRedirect("com/mojang/blaze3d/GpuFormat",
                "com/mojang/renderpearl/api/GpuFormat");
        t.registerClassRedirect("com/mojang/blaze3d/GpuFormat$ComponentType",
                "com/mojang/renderpearl/api/GpuFormat$ComponentType");
        t.registerClassRedirect("com/mojang/blaze3d/GpuOutOfMemoryException",
                "com/mojang/renderpearl/api/device/GpuOutOfMemoryException");
        t.registerClassRedirect("com/mojang/blaze3d/IndexType",
                "com/mojang/renderpearl/api/pipeline/IndexType");
        t.registerClassRedirect("com/mojang/blaze3d/PrimitiveTopology",
                "com/mojang/renderpearl/api/pipeline/PrimitiveTopology");
        t.registerClassRedirect("com/mojang/blaze3d/buffers/GpuBuffer",
                "com/mojang/renderpearl/api/buffers/GpuBuffer");
        t.registerClassRedirect("com/mojang/blaze3d/buffers/GpuBuffer$Usage",
                "com/mojang/renderpearl/api/buffers/GpuBuffer$Usage");
        t.registerClassRedirect("com/mojang/blaze3d/buffers/GpuBufferSlice",
                "com/mojang/renderpearl/api/buffers/GpuBufferSlice");
        t.registerClassRedirect("com/mojang/blaze3d/buffers/GpuBufferSlice$MappedView",
                "com/mojang/renderpearl/api/buffers/GpuBufferSlice$MappedView");
        t.registerClassRedirect("com/mojang/blaze3d/buffers/GpuFence",
                "com/mojang/renderpearl/api/commands/GpuFence");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/BufferStorage",
                "com/mojang/renderpearl/backend/opengl/BufferStorage");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/BufferStorage$Immutable",
                "com/mojang/renderpearl/backend/opengl/BufferStorage$Immutable");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/BufferStorage$Mutable",
                "com/mojang/renderpearl/backend/opengl/BufferStorage$Mutable");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/DirectStateAccess",
                "com/mojang/renderpearl/backend/opengl/DirectStateAccess");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/DirectStateAccess$Core",
                "com/mojang/renderpearl/backend/opengl/DirectStateAccess$Core");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/DirectStateAccess$Emulated",
                "com/mojang/renderpearl/backend/opengl/DirectStateAccess$Emulated");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/FrameBufferAttachment",
                "com/mojang/renderpearl/backend/opengl/FrameBufferAttachment");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/FrameBufferCache",
                "com/mojang/renderpearl/backend/opengl/FrameBufferCache");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/FrameBufferCache$CacheKey",
                "com/mojang/renderpearl/backend/opengl/FrameBufferCache$CacheKey");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlBackend",
                "com/mojang/renderpearl/backend/opengl/GlBackend");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlBuffer",
                "com/mojang/renderpearl/backend/opengl/GlBuffer");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlBuffer$Direct",
                "com/mojang/renderpearl/backend/opengl/GlBuffer$Direct");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlBuffer$Direct$1",
                "com/mojang/renderpearl/backend/opengl/GlBuffer$Direct$1");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlCommandEncoder",
                "com/mojang/renderpearl/backend/opengl/GlCommandEncoder");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlConst",
                "com/mojang/renderpearl/backend/opengl/GlConst");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlConst$1",
                "com/mojang/renderpearl/backend/opengl/GlConst$1");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlDebug",
                "com/mojang/renderpearl/backend/opengl/GlDebug");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlDebug$LogEntry",
                "com/mojang/renderpearl/backend/opengl/GlDebug$LogEntry");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlDebugLabel",
                "com/mojang/renderpearl/backend/opengl/GlDebugLabel");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlDebugLabel$Core",
                "com/mojang/renderpearl/backend/opengl/GlDebugLabel$Core");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlDebugLabel$Empty",
                "com/mojang/renderpearl/backend/opengl/GlDebugLabel$Empty");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlDebugLabel$Ext",
                "com/mojang/renderpearl/backend/opengl/GlDebugLabel$Ext");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlDevice",
                "com/mojang/renderpearl/backend/opengl/GlDevice");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlFence",
                "com/mojang/renderpearl/backend/opengl/GlFence");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlHeuristics",
                "com/mojang/renderpearl/backend/opengl/GlHeuristics");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlProgram",
                "com/mojang/renderpearl/backend/opengl/GlProgram");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlProgram$1",
                "com/mojang/renderpearl/backend/opengl/GlProgram$1");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlQueryPool",
                "com/mojang/renderpearl/backend/opengl/GlQueryPool");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlRenderPass",
                "com/mojang/renderpearl/backend/opengl/GlRenderPass");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlRenderPipeline",
                "com/mojang/renderpearl/backend/opengl/GlRenderPipeline");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlSampler",
                "com/mojang/renderpearl/backend/opengl/GlSampler");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlSampler$1",
                "com/mojang/renderpearl/backend/opengl/GlSampler$1");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlShaderModule",
                "com/mojang/renderpearl/backend/opengl/GlShaderModule");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlStateManager",
                "com/mojang/renderpearl/backend/opengl/GlStateManager");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlStateManager$BlendState",
                "com/mojang/renderpearl/backend/opengl/GlStateManager$BlendState");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlStateManager$BooleanState",
                "com/mojang/renderpearl/backend/opengl/GlStateManager$BooleanState");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlStateManager$ColorLogicState",
                "com/mojang/renderpearl/backend/opengl/GlStateManager$ColorLogicState");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlStateManager$CullState",
                "com/mojang/renderpearl/backend/opengl/GlStateManager$CullState");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlStateManager$DepthState",
                "com/mojang/renderpearl/backend/opengl/GlStateManager$DepthState");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlStateManager$PolygonOffsetState",
                "com/mojang/renderpearl/backend/opengl/GlStateManager$PolygonOffsetState");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlStateManager$ScissorState",
                "com/mojang/renderpearl/backend/opengl/GlStateManager$ScissorState");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlStateManager$TextureState",
                "com/mojang/renderpearl/backend/opengl/GlStateManager$TextureState");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlSurface",
                "com/mojang/renderpearl/backend/opengl/GlSurface");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlTexture",
                "com/mojang/renderpearl/backend/opengl/GlTexture");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlTextureView",
                "com/mojang/renderpearl/backend/opengl/GlTextureView");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlTransientMemory",
                "com/mojang/renderpearl/backend/opengl/GlTransientMemory");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlTransientMemory$Fallback",
                "com/mojang/renderpearl/backend/opengl/GlTransientMemory$Fallback");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlTransientMemory$Fallback$GlAllocation",
                "com/mojang/renderpearl/backend/opengl/GlTransientMemory$Fallback$GlAllocation");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlTransientMemory$PersistentMapping",
                "com/mojang/renderpearl/backend/opengl/GlTransientMemory$PersistentMapping");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlTransientMemory$PersistentMapping$GlAllocation",
                "com/mojang/renderpearl/backend/opengl/GlTransientMemory$PersistentMapping$GlAllocation");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlTransientMemory$PersistentMapping$Rotation",
                "com/mojang/renderpearl/backend/opengl/GlTransientMemory$PersistentMapping$Rotation");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlTransientMemory$TransientGpuBuffer",
                "com/mojang/renderpearl/backend/opengl/GlTransientMemory$TransientGpuBuffer");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/GlUtil",
                "com/mojang/renderpearl/backend/opengl/GlUtil");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/Uniform",
                "com/mojang/renderpearl/backend/opengl/Uniform");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/Uniform$Sampler",
                "com/mojang/renderpearl/backend/opengl/Uniform$Sampler");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/Uniform$Ubo",
                "com/mojang/renderpearl/backend/opengl/Uniform$Ubo");
        t.registerClassRedirect("com/mojang/blaze3d/opengl/Uniform$Utb",
                "com/mojang/renderpearl/backend/opengl/Uniform$Utb");
        t.registerClassRedirect("com/mojang/blaze3d/pipeline/BindGroupLayout",
                "com/mojang/renderpearl/api/pipeline/BindGroupLayout");
        t.registerClassRedirect("com/mojang/blaze3d/pipeline/BindGroupLayout$Builder",
                "com/mojang/renderpearl/api/pipeline/BindGroupLayout$Builder");
        t.registerClassRedirect("com/mojang/blaze3d/pipeline/BindGroupLayout$UniformDescription",
                "com/mojang/renderpearl/api/pipeline/BindGroupLayout$UniformDescription");
        t.registerClassRedirect("com/mojang/blaze3d/pipeline/BlendEquation",
                "com/mojang/renderpearl/api/pipeline/BlendEquation");
        t.registerClassRedirect("com/mojang/blaze3d/pipeline/BlendFunction",
                "com/mojang/renderpearl/api/pipeline/BlendFunction");
        t.registerClassRedirect("com/mojang/blaze3d/pipeline/ColorTargetState",
                "com/mojang/renderpearl/api/pipeline/ColorTargetState");
        t.registerClassRedirect("com/mojang/blaze3d/pipeline/ColorTargetState$WriteMask",
                "com/mojang/renderpearl/api/pipeline/ColorTargetState$WriteMask");
        t.registerClassRedirect("com/mojang/blaze3d/pipeline/CompiledRenderPipeline",
                "com/mojang/renderpearl/api/pipeline/CompiledRenderPipeline");
        t.registerClassRedirect("com/mojang/blaze3d/pipeline/DepthStencilState",
                "com/mojang/renderpearl/api/pipeline/DepthStencilState");
        t.registerClassRedirect("com/mojang/blaze3d/pipeline/RenderPipeline",
                "com/mojang/renderpearl/api/pipeline/RenderPipeline");
        t.registerClassRedirect("com/mojang/blaze3d/pipeline/RenderPipeline$Builder",
                "com/mojang/renderpearl/api/pipeline/RenderPipeline$Builder");
        t.registerClassRedirect("com/mojang/blaze3d/pipeline/RenderPipeline$Snippet",
                "com/mojang/renderpearl/api/pipeline/RenderPipeline$Snippet");
        t.registerClassRedirect("com/mojang/blaze3d/platform/BlendFactor",
                "com/mojang/renderpearl/api/pipeline/BlendFactor");
        t.registerClassRedirect("com/mojang/blaze3d/platform/BlendOp",
                "com/mojang/renderpearl/api/pipeline/BlendOp");
        t.registerClassRedirect("com/mojang/blaze3d/platform/CompareOp",
                "com/mojang/renderpearl/api/pipeline/CompareOp");
        t.registerClassRedirect("com/mojang/blaze3d/platform/PolygonMode",
                "com/mojang/renderpearl/api/pipeline/PolygonMode");
        t.registerClassRedirect("com/mojang/blaze3d/shaders/GpuDebugOptions",
                "com/mojang/renderpearl/api/device/GpuDebugOptions");
        t.registerClassRedirect("com/mojang/blaze3d/shaders/ShaderSource",
                "com/mojang/renderpearl/api/pipeline/ShaderSource");
        t.registerClassRedirect("com/mojang/blaze3d/shaders/ShaderType",
                "com/mojang/renderpearl/api/pipeline/ShaderType");
        t.registerClassRedirect("com/mojang/blaze3d/shaders/UniformType",
                "com/mojang/renderpearl/api/pipeline/UniformType");
        t.registerClassRedirect("com/mojang/blaze3d/systems/BackendCreationException",
                "com/mojang/renderpearl/api/device/BackendCreationException");
        t.registerClassRedirect("com/mojang/blaze3d/systems/BackendCreationException$Reason",
                "com/mojang/renderpearl/api/device/BackendCreationException$Reason");
        t.registerClassRedirect("com/mojang/blaze3d/systems/CommandEncoder",
                "com/mojang/renderpearl/api/commands/CommandEncoder");
        t.registerClassRedirect("com/mojang/blaze3d/systems/CommandEncoderBackend",
                "com/mojang/renderpearl/backend/api/CommandEncoderBackend");
        t.registerClassRedirect("com/mojang/blaze3d/systems/DeviceFeatures",
                "com/mojang/renderpearl/api/device/DeviceFeatures");
        t.registerClassRedirect("com/mojang/blaze3d/systems/DeviceInfo",
                "com/mojang/renderpearl/api/device/DeviceInfo");
        t.registerClassRedirect("com/mojang/blaze3d/systems/DeviceLimits",
                "com/mojang/renderpearl/api/device/DeviceLimits");
        t.registerClassRedirect("com/mojang/blaze3d/systems/DeviceType",
                "com/mojang/renderpearl/api/device/DeviceType");
        t.registerClassRedirect("com/mojang/blaze3d/systems/GpuBackend",
                "com/mojang/renderpearl/api/device/GpuBackend");
        t.registerClassRedirect("com/mojang/blaze3d/systems/GpuDevice",
                "com/mojang/renderpearl/api/device/GpuDevice");
        t.registerClassRedirect("com/mojang/blaze3d/systems/GpuDeviceBackend",
                "com/mojang/renderpearl/backend/api/GpuDeviceBackend");
        t.registerClassRedirect("com/mojang/blaze3d/systems/GpuQuery",
                "com/mojang/renderpearl/api/commands/GpuQuery");
        t.registerClassRedirect("com/mojang/blaze3d/systems/GpuQueryPool",
                "com/mojang/renderpearl/api/commands/GpuQueryPool");
        t.registerClassRedirect("com/mojang/blaze3d/systems/GpuSurface",
                "com/mojang/renderpearl/api/device/GpuSurface");
        t.registerClassRedirect("com/mojang/blaze3d/systems/GpuSurface$Configuration",
                "com/mojang/renderpearl/api/device/GpuSurface$Configuration");
        t.registerClassRedirect("com/mojang/blaze3d/systems/GpuSurface$PresentMode",
                "com/mojang/renderpearl/api/device/GpuSurface$PresentMode");
        t.registerClassRedirect("com/mojang/blaze3d/systems/GpuSurfaceBackend",
                "com/mojang/renderpearl/backend/api/GpuSurfaceBackend");
        t.registerClassRedirect("com/mojang/blaze3d/systems/HintsAndWorkarounds",
                "com/mojang/renderpearl/api/device/HintsAndWorkarounds");
        t.registerClassRedirect("com/mojang/blaze3d/systems/RenderPass",
                "com/mojang/renderpearl/api/commands/RenderPass");
        t.registerClassRedirect("com/mojang/blaze3d/systems/RenderPass$Draw",
                "com/mojang/renderpearl/api/commands/RenderPass$Draw");
        t.registerClassRedirect("com/mojang/blaze3d/systems/RenderPass$RenderArea",
                "com/mojang/renderpearl/api/commands/RenderPass$RenderArea");
        t.registerClassRedirect("com/mojang/blaze3d/systems/RenderPass$UniformUploader",
                "com/mojang/renderpearl/api/commands/RenderPass$UniformUploader");
        t.registerClassRedirect("com/mojang/blaze3d/systems/RenderPassBackend",
                "com/mojang/renderpearl/backend/api/RenderPassBackend");
        t.registerClassRedirect("com/mojang/blaze3d/systems/RenderPassDescriptor",
                "com/mojang/renderpearl/api/commands/RenderPassDescriptor");
        t.registerClassRedirect("com/mojang/blaze3d/systems/RenderPassDescriptor$Attachment",
                "com/mojang/renderpearl/api/commands/RenderPassDescriptor$Attachment");
        t.registerClassRedirect("com/mojang/blaze3d/systems/SurfaceException",
                "com/mojang/renderpearl/api/device/SurfaceException");
        t.registerClassRedirect("com/mojang/blaze3d/systems/TracyGpuProfiler",
                "com/mojang/renderpearl/frontend/TracyGpuProfiler");
        t.registerClassRedirect("com/mojang/blaze3d/systems/TransientMemory",
                "com/mojang/renderpearl/api/buffers/TransientMemory");
        t.registerClassRedirect("com/mojang/blaze3d/textures/AddressMode",
                "com/mojang/renderpearl/api/textures/AddressMode");
        t.registerClassRedirect("com/mojang/blaze3d/textures/FilterMode",
                "com/mojang/renderpearl/api/textures/FilterMode");
        t.registerClassRedirect("com/mojang/blaze3d/textures/GpuSampler",
                "com/mojang/renderpearl/api/textures/GpuSampler");
        t.registerClassRedirect("com/mojang/blaze3d/textures/GpuTexture",
                "com/mojang/renderpearl/api/textures/GpuTexture");
        t.registerClassRedirect("com/mojang/blaze3d/textures/GpuTexture$Usage",
                "com/mojang/renderpearl/api/textures/GpuTexture$Usage");
        t.registerClassRedirect("com/mojang/blaze3d/textures/GpuTextureView",
                "com/mojang/renderpearl/api/textures/GpuTextureView");
        t.registerClassRedirect("com/mojang/blaze3d/util/TransientBlockAllocator",
                "com/mojang/renderpearl/backend/util/TransientBlockAllocator");
        t.registerClassRedirect("com/mojang/blaze3d/util/TransientBlockAllocator$Allocation",
                "com/mojang/renderpearl/backend/util/TransientBlockAllocator$Allocation");
        t.registerClassRedirect("com/mojang/blaze3d/util/TransientBlockAllocator$Allocator",
                "com/mojang/renderpearl/backend/util/TransientBlockAllocator$Allocator");
        t.registerClassRedirect("com/mojang/blaze3d/util/TransientBlockAllocator$Allocator$1",
                "com/mojang/renderpearl/backend/util/TransientBlockAllocator$Allocator$1");
        t.registerClassRedirect("com/mojang/blaze3d/vertex/VertexFormat",
                "com/mojang/renderpearl/api/vertex/VertexFormat");
        t.registerClassRedirect("com/mojang/blaze3d/vertex/VertexFormat$Builder",
                "com/mojang/renderpearl/api/vertex/VertexFormat$Builder");
        t.registerClassRedirect("com/mojang/blaze3d/vertex/VertexFormatElement",
                "com/mojang/renderpearl/api/vertex/VertexFormatElement");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/Destroyable",
                "com/mojang/renderpearl/backend/vulkan/Destroyable");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/DestructionQueue",
                "com/mojang/renderpearl/backend/vulkan/DestructionQueue");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/DestructionQueue$Destroyer",
                "com/mojang/renderpearl/backend/vulkan/DestructionQueue$Destroyer");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanBackend",
                "com/mojang/renderpearl/backend/vulkan/VulkanBackend");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanCommandEncoder",
                "com/mojang/renderpearl/backend/vulkan/VulkanCommandEncoder");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanCommandEncoder$1",
                "com/mojang/renderpearl/backend/vulkan/VulkanCommandEncoder$1");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanCommandPool",
                "com/mojang/renderpearl/backend/vulkan/VulkanCommandPool");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanConst",
                "com/mojang/renderpearl/backend/vulkan/VulkanConst");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanConst$1",
                "com/mojang/renderpearl/backend/vulkan/VulkanConst$1");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanDebug",
                "com/mojang/renderpearl/backend/vulkan/VulkanDebug");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanDebug$Disabled",
                "com/mojang/renderpearl/backend/vulkan/VulkanDebug$Disabled");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanDebug$Enabled",
                "com/mojang/renderpearl/backend/vulkan/VulkanDebug$Enabled");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanDevice",
                "com/mojang/renderpearl/backend/vulkan/VulkanDevice");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanGpuBuffer",
                "com/mojang/renderpearl/backend/vulkan/VulkanGpuBuffer");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanGpuBuffer$Direct",
                "com/mojang/renderpearl/backend/vulkan/VulkanGpuBuffer$Direct");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanGpuBuffer$Direct$1",
                "com/mojang/renderpearl/backend/vulkan/VulkanGpuBuffer$Direct$1");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanGpuSampler",
                "com/mojang/renderpearl/backend/vulkan/VulkanGpuSampler");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanGpuSurface",
                "com/mojang/renderpearl/backend/vulkan/VulkanGpuSurface");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanGpuTexture",
                "com/mojang/renderpearl/backend/vulkan/VulkanGpuTexture");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanGpuTextureView",
                "com/mojang/renderpearl/backend/vulkan/VulkanGpuTextureView");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanInstance",
                "com/mojang/renderpearl/backend/vulkan/VulkanInstance");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanPhysicalDevice",
                "com/mojang/renderpearl/backend/vulkan/VulkanPhysicalDevice");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanQueryPool",
                "com/mojang/renderpearl/backend/vulkan/VulkanQueryPool");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanQueue",
                "com/mojang/renderpearl/backend/vulkan/VulkanQueue");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanQueue$Submission",
                "com/mojang/renderpearl/backend/vulkan/VulkanQueue$Submission");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanQueue$Submission$SemaphoreOp",
                "com/mojang/renderpearl/backend/vulkan/VulkanQueue$Submission$SemaphoreOp");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanQueue$Submission$SubmitStage",
                "com/mojang/renderpearl/backend/vulkan/VulkanQueue$Submission$SubmitStage");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanRenderPass",
                "com/mojang/renderpearl/backend/vulkan/VulkanRenderPass");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanRenderPass$1",
                "com/mojang/renderpearl/backend/vulkan/VulkanRenderPass$1");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanRenderPipeline",
                "com/mojang/renderpearl/backend/vulkan/VulkanRenderPipeline");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanTransientMemory",
                "com/mojang/renderpearl/backend/vulkan/VulkanTransientMemory");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanTransientMemory$TransientGpuBuffer",
                "com/mojang/renderpearl/backend/vulkan/VulkanTransientMemory$TransientGpuBuffer");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanTransientMemory$VulkanAllocation",
                "com/mojang/renderpearl/backend/vulkan/VulkanTransientMemory$VulkanAllocation");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanUtils",
                "com/mojang/renderpearl/backend/vulkan/VulkanUtils");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/VulkanUtils$DeviceUUID",
                "com/mojang/renderpearl/backend/vulkan/VulkanUtils$DeviceUUID");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/checkpoints/AbstractCheckpointStorage",
                "com/mojang/renderpearl/backend/vulkan/checkpoints/AbstractCheckpointStorage");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/checkpoints/AbstractCheckpointStorage$Checkpoint",
                "com/mojang/renderpearl/backend/vulkan/checkpoints/AbstractCheckpointStorage$Checkpoint");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/checkpoints/AbstractCheckpointStorage$Frame",
                "com/mojang/renderpearl/backend/vulkan/checkpoints/AbstractCheckpointStorage$Frame");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/checkpoints/AmdCheckpointExtension",
                "com/mojang/renderpearl/backend/vulkan/checkpoints/AmdCheckpointExtension");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/checkpoints/AmdCheckpointExtension$AmdCheckpointStorage",
                "com/mojang/renderpearl/backend/vulkan/checkpoints/AmdCheckpointExtension$AmdCheckpointStorage");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/checkpoints/CheckpointExtension",
                "com/mojang/renderpearl/backend/vulkan/checkpoints/CheckpointExtension");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/checkpoints/CheckpointExtension$CheckpointStorage",
                "com/mojang/renderpearl/backend/vulkan/checkpoints/CheckpointExtension$CheckpointStorage");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/checkpoints/CheckpointExtension$CheckpointType",
                "com/mojang/renderpearl/backend/vulkan/checkpoints/CheckpointExtension$CheckpointType");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/checkpoints/CheckpointExtension$QueueCheckpoints",
                "com/mojang/renderpearl/backend/vulkan/checkpoints/CheckpointExtension$QueueCheckpoints");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/checkpoints/CheckpointExtension$StageCheckpoint",
                "com/mojang/renderpearl/backend/vulkan/checkpoints/CheckpointExtension$StageCheckpoint");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/checkpoints/NoopCheckpointExtension",
                "com/mojang/renderpearl/backend/vulkan/checkpoints/NoopCheckpointExtension");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/checkpoints/NoopCheckpointExtension$NoopCheckpointStorage",
                "com/mojang/renderpearl/backend/vulkan/checkpoints/NoopCheckpointExtension$NoopCheckpointStorage");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/checkpoints/NvidiaCheckpointExtension",
                "com/mojang/renderpearl/backend/vulkan/checkpoints/NvidiaCheckpointExtension");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/checkpoints/NvidiaCheckpointExtension$NvidiaCheckpointStorage",
                "com/mojang/renderpearl/backend/vulkan/checkpoints/NvidiaCheckpointExtension$NvidiaCheckpointStorage");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/glsl/GlslCompiler",
                "com/mojang/renderpearl/frontend/shaders/GlslCompiler");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/glsl/ShaderCompileException",
                "com/mojang/renderpearl/util/ShaderCompileException");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/init/VulkanFeature",
                "com/mojang/renderpearl/backend/vulkan/init/VulkanFeature");
        t.registerClassRedirect("com/mojang/blaze3d/vulkan/init/VulkanPNextStruct",
                "com/mojang/renderpearl/backend/vulkan/init/VulkanPNextStruct");
    }

    /** Moves and renames outside the rendering library (45 classes). */
    private static void registerVanillaMoves(RetromodTransformer t) {
        t.registerClassRedirect("com/mojang/realmsclient/RealmsMainScreen$NotificationButton",
                "com/mojang/realmsclient/gui/RealmsHeader$NotificationButton");
        t.registerClassRedirect("net/minecraft/client/gui/screens/options/WorldOptionsScreen",
                "net/minecraft/client/gui/screens/WorldOptionsScreen");
        t.registerClassRedirect("net/minecraft/client/particle/SoulParticle",
                "net/minecraft/client/particle/EmissiveRisingParticle");
        t.registerClassRedirect("net/minecraft/client/particle/SoulParticle$EmissiveProvider",
                "net/minecraft/client/particle/EmissiveRisingParticle$EmissiveProvider");
        t.registerClassRedirect("net/minecraft/client/particle/SoulParticle$Provider",
                "net/minecraft/client/particle/EmissiveRisingParticle$Provider");
        t.registerClassRedirect("net/minecraft/client/renderer/DynamicUniforms$ChunkSectionInfo",
                "net/minecraft/client/renderer/DynamicGpuData$ChunkSectionInfo");
        t.registerClassRedirect("net/minecraft/client/renderer/DynamicUniforms$Transform",
                "net/minecraft/client/renderer/DynamicGpuData$Transform");
        t.registerClassRedirect("net/minecraft/client/renderer/ItemInHandRenderer$1",
                "net/minecraft/client/renderer/FirstPersonHandsAndItemsRenderer$1");
        t.registerClassRedirect("net/minecraft/client/renderer/ShaderManager$CompilationCache",
                "net/minecraft/client/renderer/ShaderManager$PostChainCache");
        t.registerClassRedirect("net/minecraft/core/RegistryCodecs",
                "net/minecraft/core/registries/codec/RegistryCodecs");
        t.registerClassRedirect("net/minecraft/core/RegistrySetBuilder$LazyHolder",
                "net/minecraft/core/registries/PatchedRegistry$LazyHolder");
        t.registerClassRedirect("net/minecraft/resources/HolderSetCodec",
                "net/minecraft/core/registries/codec/HolderSetCodec");
        t.registerClassRedirect("net/minecraft/resources/RegistryFileCodec",
                "net/minecraft/core/registries/codec/RegistryFileCodec");
        t.registerClassRedirect("net/minecraft/resources/RegistryFixedCodec",
                "net/minecraft/core/registries/codec/RegistryFixedCodec");
        t.registerClassRedirect("net/minecraft/server/commands/ItemCommands",
                "net/minecraft/server/commands/item/ItemCommands");
        t.registerClassRedirect("net/minecraft/server/packs/AbstractPackResources",
                "net/minecraft/server/packs/AbstractPackMetadataResources");
        t.registerClassRedirect("net/minecraft/server/packs/CompositePackResources",
                "net/minecraft/server/packs/OverlayedPackResources");
        t.registerClassRedirect("net/minecraft/util/datafix/fixes/AbstractBlockPropertyFix",
                "net/minecraft/util/datafix/fixes/LegacyAbstractBlockPropertyFix");
        t.registerClassRedirect("net/minecraft/util/datafix/fixes/BlockPropertyRenameAndFix",
                "net/minecraft/util/datafix/fixes/LegacyBlockPropertyRenameAndFix");
        t.registerClassRedirect("net/minecraft/util/datafix/fixes/BlockRenameFix",
                "net/minecraft/util/datafix/fixes/LegacyBlockRenameFix");
        t.registerClassRedirect("net/minecraft/util/datafix/fixes/BlockRenameFix$1",
                "net/minecraft/util/datafix/fixes/LegacyBlockRenameFix$1");
        t.registerClassRedirect("net/minecraft/world/clock/ServerClockManager$ClockInstance",
                "net/minecraft/world/clock/ServerClockManager$ServerClockInstance");
        t.registerClassRedirect("net/minecraft/world/entity/ai/goal/CatLieOnBedGoal",
                "net/minecraft/world/entity/ai/goal/CatLieOnBlockGoal");
        t.registerClassRedirect("net/minecraft/world/entity/monster/EnderMan",
                "net/minecraft/world/entity/monster/Enderman");
        t.registerClassRedirect("net/minecraft/world/entity/monster/EnderMan$EndermanFreezeWhenLookedAt",
                "net/minecraft/world/entity/monster/Enderman$EndermanFreezeWhenLookedAt");
        t.registerClassRedirect("net/minecraft/world/entity/monster/EnderMan$EndermanLookForPlayerGoal",
                "net/minecraft/world/entity/monster/Enderman$EndermanLookForPlayerGoal");
        t.registerClassRedirect("net/minecraft/world/entity/monster/EnderMan$EndermanTakeBlockGoal",
                "net/minecraft/world/entity/monster/Enderman$EndermanTakeBlockGoal");
        t.registerClassRedirect("net/minecraft/world/level/biome/Climate$SpawnFinder$Result",
                "net/minecraft/world/level/levelgen/NoiseSpawnFinder$Result");
        t.registerClassRedirect("net/minecraft/world/level/block/RedStoneWireBlock",
                "net/minecraft/world/level/block/RedstoneWireBlock");
        t.registerClassRedirect("net/minecraft/world/level/block/RedStoneWireBlock$1",
                "net/minecraft/world/level/block/RedstoneWireBlock$1");
        t.registerClassRedirect("net/minecraft/world/level/levelgen/DensityFunction",
                "net/minecraft/world/level/levelgen/densityfunction/DensityFunction");
        t.registerClassRedirect("net/minecraft/world/level/levelgen/DensityFunctions",
                "net/minecraft/world/level/levelgen/densityfunction/DensityFunctions");
        t.registerClassRedirect("net/minecraft/world/level/levelgen/DensityFunctions$HolderHolder",
                "net/minecraft/world/level/levelgen/densityfunction/DensityFunctions$HolderHolder");
        t.registerClassRedirect("net/minecraft/world/level/levelgen/DensityFunctions$Spline$Coordinate",
                "net/minecraft/world/level/levelgen/densityfunction/op/SplineFunction$Coordinate");
        t.registerClassRedirect("net/minecraft/world/level/levelgen/SurfaceRules$NoiseThresholdConditionSource",
                "net/minecraft/world/level/levelgen/material/condition/NoiseThresholdCondition");
        t.registerClassRedirect("net/minecraft/world/level/levelgen/SurfaceRules$StoneDepthCheck",
                "net/minecraft/world/level/levelgen/material/condition/StoneDepthCondition");
        t.registerClassRedirect("net/minecraft/world/level/levelgen/SurfaceRules$VerticalGradientConditionSource",
                "net/minecraft/world/level/levelgen/material/condition/VerticalGradientCondition");
        t.registerClassRedirect("net/minecraft/world/level/levelgen/SurfaceRules$WaterConditionSource",
                "net/minecraft/world/level/levelgen/material/condition/WaterCondition");
        t.registerClassRedirect("net/minecraft/world/level/levelgen/SurfaceRules$YConditionSource",
                "net/minecraft/world/level/levelgen/material/condition/YCondition");
        t.registerClassRedirect("net/minecraft/world/level/levelgen/SurfaceSystem$1",
                "net/minecraft/world/level/levelgen/material/MaterialSystem$1");
        t.registerClassRedirect("net/minecraft/world/level/levelgen/feature/configurations/BlockColumnConfiguration$Layer",
                "net/minecraft/world/level/levelgen/feature/BlockColumnFeature$Layer");
        t.registerClassRedirect("net/minecraft/world/level/levelgen/feature/configurations/TemplateFeatureConfiguration$TemplateEntry",
                "net/minecraft/world/level/levelgen/feature/TemplateFeature$TemplateEntry");
        t.registerClassRedirect("net/minecraft/world/level/levelgen/structure/placement/StructurePlacement$ExclusionZone",
                "net/minecraft/world/level/levelgen/structure/placement/AbstractSpreadingStructurePlacement$ExclusionZone");
        t.registerClassRedirect("net/minecraft/world/level/levelgen/structure/placement/StructurePlacement$FrequencyReducer",
                "net/minecraft/world/level/levelgen/structure/placement/AbstractSpreadingStructurePlacement$FrequencyReducer");
        t.registerClassRedirect("net/minecraft/world/level/storage/loot/ValidationContext$MissingReferenceProblem",
                "net/minecraft/world/level/storage/loot/ValidationContext$RecursiveElementReferenceProblem");
    }
}
